name: Flutter CI/CD

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.44.8"
          channel: stable

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.44.8"
          channel: stable

      - name: Get Dependencies
        run: flutter pub get

      - name: Configure MSVC (Workaround)
        run: echo "CL=/D_SILENCE_EXPERIMENTAL_COROUTINE_DEPRECATION_WARNINGS" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Build Windows
        run: flutter build windows --release

      - name: Compress Windows Artifact
        run: Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath Release.zip
        shell: powershell

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-zip
          path: Release.zip

  release:
    needs: [build-android, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download Android Artifact
        uses: actions/download-artifact@v4
        with:
          name: android-apk
          path: artifacts/android

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-zip
          path: artifacts/windows

      - name: Release to GitHub
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v1.0.${{ github.run_number }}
          # 标签就用触发 workflow 的那个 tag，例如 v1.0.5
          # 也可以显式写 tag_name: ${{ github.ref_name }}
          files: |
            artifacts/android/app-release.apk
            artifacts/windows/Release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}