name: Flutter CI/CD

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
#  build-android:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Setup Java
#        uses: actions/setup-java@v4
#        with:
#          distribution: temurin
#          java-version: "17"
#
#      - name: Setup Flutter
#        uses: subosito/flutter-action@v2
#        with:
#          flutter-version: "3.44.8"
#          channel: stable
#
#      - name: Get Dependencies
#        run: flutter pub get
#
#      - name: Build APK
#        run: flutter build apk --release
#
#      - name: Upload Android Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: android-apk
#          path: build/app/outputs/flutter-apk/app-release.apk
#          retention-days: 1

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.44.8"
          channel: stable

      - name: Get Dependencies
        run: flutter pub get

      - name: Configure MSVC (Workaround)
        run: echo "CL=/D_SILENCE_EXPERIMENTAL_COROUTINE_DEPRECATION_WARNINGS" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Build Windows
        run: flutter build windows --release

      - name: Compress Windows Artifact
        run: Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath Release.zip
        shell: powershell

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-zip
          path: Release.zip
          retention-days: 1

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.44.8"
          channel: stable

      - name: Get Dependencies
        run: flutter pub get

      # --no-codesign 参数用于在没有签名证书的情况下生成构建产物
      - name: Build IOS (No Codesign)
        run: flutter build ios --release --no-codesign

      - name: Create Unsigned IPA
        run: |
          mkdir -p build/ios/ipa/Payload
          cp -r build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -r ../Runner_unsigned.ipa Payload

      # 压缩 IPA
      - name: Compress IPA
        run: |
          cd build/ios/ipa  # 进入 ipa 目录
          zip -r ios-build.zip ../Runner_unsigned.ipa  # 使用相对路径

#      - name: Compress iOS Artifact
#        # 将生成的 app 包压缩，方便上传
#        run: zip -r ios-build.zip build/ios/iphoneos/Runner.app

#      - name: Upload iOS Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: ios-zip
#          path: ios-build.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-zip
          path: build/ios/ipa/ios-build.zip
          retention-days: 1

  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.44.8"
          channel: stable

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release

      - name: Compress Web Artifact
        run: zip -r web-build.zip build/web

      - name: Upload Web Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-zip
          path: web-build.zip
          retention-days: 1

  release:
#    needs: [build-android, build-ios, build-windows, build-web]
    needs: [build-ios, build-windows, build-web]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Read pubspec version
        id: vars
        run: |
          VERSION=$(grep -m1 '^version:' pubspec.yaml | sed 's/version: //' | cut -d'+' -f1)
          echo "VERSION=$VERSION" >>$GITHUB_OUTPUT

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Release to GitHub
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.vars.outputs.VERSION }}
          overwrite_files: true
          files: |
            artifacts/ios-zip/ios-build.zip
            artifacts/windows-zip/Release.zip
            artifacts/web-zip/web-build.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify Server
        run: |
          VERSION="${{ steps.vars.outputs.VERSION }}"
          REPO="${{ github.repository }}"
          
          # 拼接所有平台的下载链接
          IOS_URL="https://github.com/$REPO/releases/download/$VERSION/ios-build.zip"
          WINDOWS_URL="https://github.com/$REPO/releases/download/$VERSION/Release.zip"
          WEB_URL="https://github.com/$REPO/releases/download/$VERSION/web-build.zip"

          echo "Notifying server for version $VERSION..."

          curl -X POST https://www.yuumi.cc/webhook/deploy \
          -H "Content-Type: application/json" \
          -d "{
            \"status\": \"success\",
            \"version\": \"$VERSION\",
            \"ios_url\": \"$IOS_URL\",
            \"windows_url\": \"$WINDOWS_URL\",
            \"web_url\": \"$WEB_URL\"
          }"